export const invoiceTableConstant = {
    cols: [
        { field: '', header: '#', class: 'text-center', width: '2rem' },
        {
            field: 'created_at',
            header: 'Date / Heure',
            class: 'text-center',
            width: '10rem',
        },
        {
            field: 'reference',
            header: 'Référence',
            class: 'text-center',
            width: '10rem',
        },
        { field: 'operation', header: 'Opération', width: '10rem' },
        {
            field: 'qte',
            header: 'Quantité',
            class: 'text-center',
            width: '4rem',
        },
        {
            field: 'prix_unitaire',
            header: 'PU (Fcfa)',
            class: 'text-center',
            width: '4rem',
        },
        {
            field: 'prix_ht',
            header: 'Montant HT (Fcfa)',
            class: 'text-center',
            width: '4rem',
        },
        {
            field: 'type_paiement',
            header: 'Type paiement',
            class: 'text-center',
            width: '12rem',
        },
        {
            field: 'statut',
            header: 'Etat facture',
            class: 'text-center',
            width: '4rem',
        },
        {
            field: 'updated_at',
            header: 'Date Etat',
            class: 'text-center',
            width: '12rem',
        },
        { field: '', header: 'Actions', class: 'text-center', width: '4rem' },
    ],
    globalFilterFields: [
        'created_at',
        'reference',
        'operation',
        'qte',
        'prix_unitaire',
        'prix_ttc',
        'statut',
        'updated_at',
    ],
};
