export enum Status {
    ACTIVE = 'COMMON.ACTIVE',
    INACTIVE = 'COMMON.INACTIVE',
    BLOCKED = 'COMMON.BLOCKED',
    PENDING = 'COMMON.PENDING',
}

export enum StatusStyle {
    ACTIVE = 'COMMON.ACTIVE_STYLE',
    INACTIVE = 'COMMON.INACTIVE_STYLE',
    BLOCKED = 'COMMON.BLOCKED_STYLE',
    PENDING = 'COMMON.PENDING_STYLE',
}
