export interface DetailsDemandResponse {
    error: boolean;
    message: string;
    data: DetailsDemand;
}

export interface DetailsDemand {
    id: number;
    numero_demande: string;
    description: string;
    justificatif: string;
    operation: string;
    bac_a_pioche: any;
    cloture_a: any;
    nb_demande_soumises: number;
    nb_demande_traitees: number;
    nb_demande_cloturees: number;
    initie_par: number;
    recu_paiement: any;
    niveau_un_uuid: string | null;
    niveau_deux_uuid: string | null;
    niveau_trois_uuid: string | null;
    formule_uuid: string;
    usage_id: number;
    intervenant_id: number | null;
    traite_a: any;
    traite_par: any;
    cloture_par: any;
    abandonne_a: any;
    abandonne_par: any;
    acquitte_a: any;
    acquitte_par: any;
    commentaire_traitement: string | null;
    commentaire_cloture: string | null;
    nb_demande_identifiees: string;
    nb_demande_echouees: string;
    type: string;
    finalise_a: any;
    finalise_par: any;
    commentaire_finalisation: string | null;
    montant_formule: any;
    nb_cycle: number;
    nb_demande_crees: number;
    accepte: any;
    equipe_id: any;
    type_paiement: any;
    nb_sim_affectees: number;
    accepte_approbation: any;
    commentaire_approbation: any;
    approuve_par: any;
    approuve_a: any;
    delai_ack: number;
    delai_traitement: number;
    delai_cloture: number;
    delai_escalade: number;
    source: string;
    date_soumission_facture: any;
    etat_facture: string;
    recuperer_par: any;
    recuperer_a: any;
    commentaire_livraison: any;
    livre_par: any;
    livre_a: any;
    etat_soumission: string;
    etat_traitement: string | null;
    etat_finalisation: string | null;
    etat_cloture: string | null;
    statut: string;
    traitement: string;
    notation_cloture: any;
    created_at: string;
    updated_at: string;
    formule: string;
    usage_nom: string;
    niveau_uns_code: string | null;
    niveau_deux_code: string | null;
    niveau_trois_code: string | null;
    niveau_uns_nom: string | null;
    niveau_deux_nom: string | null;
    niveau_trois_nom: string | null;
    demandeur_nom: string;
    demandeur_prenoms: string;
    demandeur_contacts: string;
    demandeur_email: string;
    demandeur_matricule: string;
    intervenant: any;
    finalisateur: any;
    approbateur: any;
    livreur: any;
    qte: number;
    prix_unitaire: number;
    prix_ht: number;
    tva: string;
    prix_tva: string;
    prix_ttc: number;
    montant_paye: string;
    date_paiement: string | null;
    date_limite: string;
    commentaire_facture: string | null;
    accepte_facture: string | null;
    prix_ttc_lettres: string;
    montant_total: string;
    impaye_anterieur: string;
    orangeInfo: OrangeInfoInterface;
    clientInfo: ClientInfoInterface;
    soldeDisponible: string;
    SoldeEngage: string;
    SoldeRestant: number;
}

interface InvoiceInterface {
    id: number;
    reference: string;
    initie_par: number;
    traite_a: string | null;
    traite_par: string | null;
    approuve_par: string | null;
    approuve_a: string | null;
    numero_demande: string;
    operation: string;
    qte: number;
    prix_unitaire: number;
    prix_ht: number;
    tva: string;
    prix_tva: string;
    prix_ttc: number;
    statut: string;
    montant_paye: string;
    date_paiement: string | null;
    date_limite: string;
    etat_facture: string;
    type_paiement: string | null;
    created_at: string;
    updated_at: string;
    commentaire_facture: string | null;
    accepte_facture: string | null;
    prix_ttc_lettres: string;
    montant_total: string;
    impaye_anterieur: string;
    orangeInfo: OrangeInfoInterface;
    clientInfo: ClientInfoInterface;
    soldeDisponible: string;
    SoldeEngage: string;
    SoldeRestant: number;
}

export interface OrangeInfoInterface {
    id: number;
    rccm: string;
    cc: string;
    adresse: string;
    email: string;
    contact_1: string;
    contact_2: string;
    site_web: string;
    date_fondation: string;
    ordre: string;
    banque: string;
    compte: string;
    mobile_money: string;
    acompte: string;
    solde: string;
    logo: string;
    created_at: string | null;
    updated_at: string | null;
}

export interface ClientInfoInterface {
    adresse: string;
    compte_client: string;
    nom_gerant: string;
    contact_admin_tenant: string;
    email_admin_tenant: string;
    nom_tenant: string;
    segment_client: string | null;
}
