export enum AccessLogsActions {
    LOGIN = 'SETTINGS_SECURITY.ACCESS_LOGS.FILTER.ACTIONS_OPTIONS.LOGIN',
    LOGOUT = 'SETTINGS_SECURITY.ACCESS_LOGS.FILTER.ACTIONS_OPTIONS.LOGOUT',
    ATTEMPTED_LOGIN = 'SETTINGS_SECURITY.ACCESS_LOGS.FILTER.ACTIONS_OPTIONS.ATTEMPTED_LOGIN',
    BLOCKED_ATTEMPTED_LOGIN = 'SETTINGS_SECURITY.ACCESS_LOGS.FILTER.ACTIONS_OPTIONS.BLOCKED_ATTEMPTED_LOGIN',
    ATTEMPTS_EXCEEDED = 'SETTINGS_SECURITY.ACCESS_LOGS.FILTER.ACTIONS_OPTIONS.ATTEMPTS_EXCEEDED',
}
