import { BADGE_ETAPE } from '../../../../../../shared/constants/badge-etape.constant';

export const WAITING_QUEUE_STEP_ENUM = {
    SUBMISSION: BADGE_ETAPE.SOUMISSION,
    TREATMENT: BADGE_ETAPE.TRAITEMENT,
    FINALIZATION: BADGE_ETAPE.FINALISATEUR,
    CLOSURE: BADGE_ETAPE.CLOTURE,
} as const;

export type T_WAITING_QUEUE_STEP_ENUM =
    (typeof WAITING_QUEUE_STEP_ENUM)[keyof typeof WAITING_QUEUE_STEP_ENUM];
