export enum Status {
    APPROVED = 'REQUESTS.ALL.STATUS.APPROVED',
    REJECTED = 'REQUESTS.ALL.STATUS.REJECTED',
    ABANDONED = 'REQUESTS.ALL.STATUS.ABANDONED',
    'IN_PROGRESS' = 'REQUESTS.ALL.STATUS.IN_PROGRESS',
    TERMINATED = 'REQUESTS.ALL.STATUS.TERMINATED',
    CONFIRMED = 'REQUESTS.ALL.STATUS.CONFIRMED',
}
