export enum Channels {
    'PUSH' = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.PUSH',
    'EMAIL' = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.EMAIL',
    'SMS' = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.SMS',
}
