export enum MessagingTypeEnum {
    TIP = 'COMMUNICATION.MESSAGING.ENUMS.TYPE.TIP',
    EDUCATION = 'COMMUNICATION.MESSAGING.ENUMS.TYPE.EDUCATION',
    INFO = 'COMMUNICATION.MESSAGING.ENUMS.TYPE.INFO',
    AWARENESS = 'COMMUNICATION.MESSAGING.ENUMS.TYPE.AWARENESS',
}
