export enum MessagingChannelsEnum {
    PUSH = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.PUSH',
    MAIL = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.EMAIL',
    SMS = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.SMS',
}

export enum ChannelsStyle {
    PUSH = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.PUSH_STYLE',
    MAIL = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.EMAIL_STYLE',
    SMS = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.SMS_STYLE',
}
