import { BADGE_ETAT } from '../../../../../../shared/constants/badge-etat.contant';

export const TREATMENT_MONITORING_STATE_ENUM = {
    RECEIVE: BADGE_ETAT.RECU,
    IN_PROGRESS: BADGE_ETAT.EN_COURS,
    DONE: BADGE_ETAT.TERMINE,
    IN_WAITING: BADGE_ETAT.EN_ATTENTE,
    LET_DOWN: BADGE_ETAT.ABANDONNE,
    ACCEPT: BADGE_ETAT.ACCEPTE,
    REJECT: BADGE_ETAT.REJETE,
    DO: BADGE_ETAT.EFFECTUE,
    APPROVE: BADGE_ETAT.APPROUVE,
    PARTIAL: BADGE_ETAT.PARTIEL,
    REFUSE: BADGE_ETAT.REFUSE,
} as const;

export type T_TREATMENT_MONITORING_STATE_ENUM =
    typeof TREATMENT_MONITORING_STATE_ENUM[keyof typeof TREATMENT_MONITORING_STATE_ENUM];
