import { BADGE_ETAPE } from '../../../../../../shared/constants/badge-etape.constant';

export const TREATMENT_MONITORING_STEP_ENUM = {
    SUBMISSION: BADGE_ETAPE.SOUMISSION,
    TREATMENT: BADGE_ETAPE.TRAITEMENT,
    FINALIZATION: BADGE_ETAPE.FINALISATEUR,
    CLOSURE: BADGE_ETAPE.CLOTURE,
} as const;

export type T_TREATMENT_MONITORING_STEP_ENUM =
    (typeof TREATMENT_MONITORING_STEP_ENUM)[keyof typeof TREATMENT_MONITORING_STEP_ENUM];
