export interface SlaContactsInterface {
    id: string;
    tenant_code: string;
    nom_tenant: string;
    slug: string;
    domaine_activite: string;
    email_diffusion: string;
    email_diffusion_tenant: string;
    url_detection_appro: string;
    intervenant_id: number | null;
    nom_admin_tenant: string;
    contact_admin_tenant: string;
    email_admin_tenant: string;
    nom_escaladen_tenant: string;
    contact_escaladen_tenant: string;
    email_escaladen_tenant: string;
    nom_gestionnaire: string | null;
    contact_gestionnnaire: string;
    email_gestionnnaire: string | null;
    escalade_tenant_id: string;
    commercial_id: number;
    nom_commercial: string;
    contact_commercial: string;
    email_commercial: string;
    senior_manager_id: number;
    nom_senior_manager: string;
    contact_senior_manager: string;
    email_senior_manager: string;
    description: string;
    url_backend: string;
    url_minio: string;
    url_nodered: string;
    url_deploy_profil_supervision: string;
    url_frontend: string;
    url_demandes_sla: string;
    url_dossiers_demandes: string;
    url_systeme_paiement: string | null;
    ws_server: string;
    nb_max_users: number;
    lien_dashboard_grafana: string;
    lien_dashboard_appro: string;
    lien_dashboard_rejets: string;
    logo_tenant: string;
    application: string;
    suffixe_email: string;
    url_consommation: string;
    compte_client: string;
    segment_client: string | null;
    forme_juridique_code: string;
    regime_code: string;
    adresse: string;
    numero_rccm: string;
    forme_juridique: string;
    gestionnaire_tenant_id: string;
    fichier_rccm: string;
    numero_cc: string;
    regime: string;
    centre: string;
    fichier_dfe: string;
    admin_tenant_id: string;
    contact_tenant_tenant: string;
    contact_gestionnaire_tenant: string;
    email_gerant: string;
    contact_gerant: string;
    nom_gerant: string;
    piece_gerant: string;
    created_at: string;
    updated_at: string;
    nom_gestionnaire_tenant: string;
    prenoms_gestionnaire_tenant: string;
    email_gestionnaire_tenant: string;
    nom_escalade_tenant: string;
    prenoms_escalade_tenant: string;
    contact_escalade_tenant: string;
    email_escalade_tenant: string;
    username_escalade_tenant: string;
    username_gestionnaire_tenant: string;
    username_admin_tenant: string;
}

export interface SlaContactsApiResponseInterface {
    error: boolean;
    message: string;
    data: SlaContactsInterface;
}
