export const MODULE_TREATMENT_CUSTOMERS_ACTIVATE = {
    REQUESTS_SERVICE: 'Demande de service',
    REPORT_ROUTE: 'Operations supervision',
};

export type T_MODULE_TREATMENT_CUSTOMERS_ACTIVATE =
    (typeof MODULE_TREATMENT_CUSTOMERS_ACTIVATE)[keyof typeof MODULE_TREATMENT_CUSTOMERS_ACTIVATE];
