export const WAITING_QUEUE_TABLE = {
    cols: [
        { field: '', header: '#', class: 'text-center', width: '2rem' },
        {
            field: 'created_at',
            header: 'Date / Heure',
            class: 'text-center',
            width: '12rem',
        },
        { field: 'operation', header: 'Type Opération', width: '16rem' },
        {
            field: 'numero_demande',
            header: 'N° Dossier',
            class: 'text-center',
            width: '12rem',
        },
        {
            field: 'nom_client',
            header: 'Client',
            class: 'text-center',
            width: '12rem',
        },
        {
            field: 'compte_client',
            header: 'Compte client',
            class: 'text-center',
            width: '8rem',
        },
        {
            field: 'statut',
            header: 'Etape',
            class: 'text-center',
            width: '8rem',
        },
        {
            field: 'traitement',
            header: 'Etat',
            class: 'text-center',
            width: '8rem',
        },
        {
            field: 'demandeur',
            header: 'Demandeur',
            class: 'text-center',
            width: '15rem',
        },
        { field: '', header: 'Actions', class: 'text-center', width: '6rem' },
    ],
    globalFilterFields: [
        'created_at',
        'operation',
        'numero_demande',
        'nom_client',
        'compte_client',
        'statut',
        'traitement',
        'updated_at',
        'demandeur',
    ],
};
