export const PROFILES_AUTHORIZATIONS_STATE_ENUM = {
    ACTIVE: 'actif',
    INACTIVE: 'inactif',
} as const;

export type T_PROFILES_AUTHORIZATIONS_STATE_ENUM =
    typeof PROFILES_AUTHORIZATIONS_STATE_ENUM[keyof typeof PROFILES_AUTHORIZATIONS_STATE_ENUM];
