export enum Status {
    PENDING = 'pending',
    APPROVED = 'approved',
    REJECTED = 'rejected',
    ABANDONED = 'abandoned',
    'IN_PROGRESS' = 'in-progress',
    TERMINATED = 'terminated',
    CONFIRMED = 'confirmed',
}

export enum StatusStyle {
    APPROVED = 'REQUESTS.ALL.STATUS.APPROVED_STYLE',
    REJECTED = 'REQUESTS.ALL.STATUS.REJECTED_STYLE',
    ABANDONED = 'REQUESTS.ALL.STATUS.ABANDONED_STYLE',
    'IN_PROGRESS' = 'REQUESTS.ALL.STATUS.IN_PROGRESS_STYLE',
    TERMINATED = 'REQUESTS.ALL.STATUS.TERMINATED_STYLE',
    CONFIRMED = 'REQUESTS.ALL.STATUS.CONFIRMED_STYLE',
    PENDING = 'REQUESTS.ALL.STATUS.PENDING_STYLE',
}
