export enum ActionDropdown {
    ACTIVE = 'COMMON.ACTIVATED',
    INACTIVE = 'COMMON.DEACTIVATED',
    PUBLISHED = 'COMMON.PUBLISHED',
    UNPUBLISHED = 'COMMON.UNPUBLISHED',
    AFFECTED = 'COMMON.AFFECTED',
}
