export enum LocationName {
    RESIDENCE_PLACE = 'COMMON.RESIDENCE_PLACE',
    ACTIVITY_PLACE = 'COMMON.ACTIVITY_PLACE',
    TRANSIT_PLACE = 'COMMON.TRANSIT_PLACE',
    PLACE_NOT_PROVIDED = 'COMMON.PLACE_NOT_PROVIDED',
}
