export enum Profiles {
    SUPERVISOR = 'COMMON.SUPERVISOR',
    LEADER = 'COMMON.LEADER',
    AGENT = 'COMMON.AGENT',
}

export enum ProfilesStyle {
    SUPERVISOR = 'COMMON.SUPERVISOR_STYLE',
    LEADER = 'COMMON.LEADER_STYLE',
    AGENT = 'COMMON.AGENT_STYLE',
}
