export enum Status {
    PENDING = 'REPORT_STATES.ALL.STATUS.PENDING',
    PROCESSING = 'REPORT_STATES.ALL.STATUS.PROCESSING',
    DONE = 'REPORT_STATES.ALL.STATUS.DONE',
    FAILED = 'REPORT_STATES.ALL.STATUS.FAILED',
}

export enum StatusStyle {
    PENDING = 'REPORT_STATES.ALL.STATUS.PENDING_STYLE',
    PROCESSING = 'REPORT_STATES.ALL.STATUS.PROCESSING_STYLE',
    DONE = 'REPORT_STATES.ALL.STATUS.DONE_STYLE',
    FAILED = 'REPORT_STATES.ALL.STATUS.FAILED_STYLE',
}
