export enum Status {
    PENDING = 'COMMON.PENDING',
    PROCESSING = 'COMMON.PROCESSING',
    DONE = 'COMMON.DONE',
    FAILED = 'COMMON.FAILED',
}

export enum StatusStyle {
    PENDING = 'COMMON.PENDING_STYLE',
    PROCESSING = 'COMMON.PROCESSING_STYLE',
    DONE = 'COMMON.DONE_STYLE',
    FAILED = 'COMMON.FAILED_STYLE',
}
