export enum TasksActionsTypes {
    ANALYSIS = 'ACTIONS.TYPES.ANALYSIS',
    TREATMENT = 'ACTIONS.TYPES.TREATMENT',
    VERIFICATION = 'ACTIONS.TYPES.VERIFICATION',
    CORRECTION = 'ACTIONS.TYPES.CORRECTION',
    VALIDATION = 'VALIDATION',
    OTHER = 'ACTIONS.TYPES.OTHER',
}
