export enum Conformity {
    CONFORM = 'COMMON.CONFORM',
    NON_CONFORM = 'COMMON.NON_CONFORM',
    IN_PROGRESS = 'COMMON.IN_PROGRESS',
    UNKNOWN = 'COMMON.UNKNOWN',
}

export enum ConformityStyle {
    CONFORM = 'COMMON.CONFORM_STYLE',
    NON_CONFORM = 'COMMON.NON_CONFORM_STYLE',
    IN_PROGRESS = 'COMMON.IN_PROGRESS_STYLE',
    UNKNOWN = 'COMMON.UNKNOWN_STYLE',
}
