export enum TasksActionsTypes {
    ANALYSIS = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.ANALYSIS',
    TREATMENT = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.TREATMENT',
    VERIFICATION = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.VERIFICATION',
    CORRECTION = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.CORRECTION',
    VALIDATION = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.VALIDATION',
    OTHER = 'PROCESSING.TASKS.ACTIONS.DIALOG.FORM.TYPE_ACTIONS_OPTIONS.OTHER',
}
