export const CUSTOMERS_ACTIVATE_TABLE = {
    cols: [
        {
            field: '',
            header: '#',
            class: 'text-center',
            maxWidth: '3rem',
            width: '3rem',
        },
        {
            field: 'created_at',
            header: 'Date / Heure',
            class: 'text-center',
            width: '8rem',
            maxWidth: '8rem',
        },
        {
            field: 'compte_client',
            header: 'Compte Client',
            class: 'text-center',
            width: 'auto',
            maxWidth: 'auto',
        },
        {
            field: 'nom_client',
            header: 'Nom Commercial',
            class: 'text-center',
            width: 'auto',
            maxWidth: 'auto',
        },
        {
            field: 'statut',
            header: 'Etape',
            class: 'text-center',
            width: '8rem',
            maxWidth: '8rem',
        },
        {
            field: 'traitement',
            header: 'Etat',
            class: 'text-center',
            width: '8rem',
            maxidth: '8rem',
        },
        {
            field: 'updated_at',
            header: 'Date Etat',
            class: 'text-center',
            width: '8rem',
            maxWidth: '8rem',
        },
        // {
        //   field: 'demandeur',
        //   header: 'Demandeur',
        //   class: 'text-center',
        //   width: '10rem',
        // },
        { field: '', header: 'Actions', class: 'text-center', width: '16rem' },
    ],
    globalFilterFields: [
        'created_at',
        'nom_client',
        'compte_client',
        'statut',
        'traitement',
        'updated_at',
        // 'demandeur',
    ],
};
