export enum Status {
    COMPLETED = 'COMMON.COMPLETED',
    NOT_COMPLETED = 'COMMON.NOT_COMPLETED',
}

export enum StatusStyle {
    COMPLETED = 'COMMON.COMPLETED_STYLE',
    NOT_COMPLETED = 'COMMON.NOT_COMPLETED_STYLE',
}
