export const CUSTOMERS_ACTIVATE_IDENTIFICATION_ENUM = {
    RELIABLE: 'fiable',
    IN_PROGRESS: 'en-cours',
    UNRELIABLE: 'non-fiable',
} as const;

export type T_CUSTOMERS_ACTIVATE_IDENTIFICATION_ENUM =
    typeof CUSTOMERS_ACTIVATE_IDENTIFICATION_ENUM[keyof typeof CUSTOMERS_ACTIVATE_IDENTIFICATION_ENUM];
