import { BADGE_ETAPE } from '../../../../../../shared/constants/badge-etape.constant';

export const CUSTOMERS_ACTIVATE_STEP_ENUM = {
    SUBMISSION: BADGE_ETAPE.SOUMISSION,
    TREATMENT: BADGE_ETAPE.TRAITEMENT,
    FINALIZATION: BADGE_ETAPE.FINALISATEUR,
    CLOSURE: BADGE_ETAPE.CLOTURE,
} as const;

export type T_CUSTOMERS_ACTIVATE_STEP_ENUM =
    typeof CUSTOMERS_ACTIVATE_STEP_ENUM[keyof typeof CUSTOMERS_ACTIVATE_STEP_ENUM];
