export enum Channels {
    PUSH = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.PUSH',
    MAIL = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.EMAIL',
    SMS = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.SMS',
    WHATSAPP = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.WHATSAPP',
    TELEGRAM = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.TELEGRAM',
}

export enum ChannelsStyle {
    PUSH = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.PUSH_STYLE',
    MAIL = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.EMAIL_STYLE',
    SMS = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.SMS_STYLE',
    WHATSAPP = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.WHATSAPP_STYLE',
    TELEGRAM = 'COMMUNICATION.MESSAGING.ENUMS.CHANNELS.TELEGRAM_STYLE',
}
