export enum Status {
    APPROVED = 'REPORT_STATES.ALL.STATUS.APPROVED',
    REJECTED = 'REPORT_STATES.ALL.STATUS.REJECTED',
    ABANDONED = 'REPORT_STATES.ALL.STATUS.ABANDONED',
    'IN_PROGRESS' = 'REPORT_STATES.ALL.STATUS.IN_PROGRESS',
    TERMINATED = 'REPORT_STATES.ALL.STATUS.TERMINATED',
    CONFIRMED = 'REPORT_STATES.ALL.STATUS.CONFIRMED',
}

export enum StatusStyle {
    APPROVED = 'REPORT_STATES.ALL.STATUS.APPROVED_STYLE',
    REJECTED = 'REPORT_STATES.ALL.STATUS.REJECTED_STYLE',
    ABANDONED = 'REPORT_STATES.ALL.STATUS.ABANDONED_STYLE',
    'IN_PROGRESS' = 'REPORT_STATES.ALL.STATUS.IN_PROGRESS_STYLE',
    TERMINATED = 'REPORT_STATES.ALL.STATUS.TERMINATED_STYLE',
    CONFIRMED = 'REPORT_STATES.ALL.STATUS.CONFIRMED_STYLE',
}
