
export const enum EndPointUrl {
    PATRIMOINE_SIM_TRANSACTIONS_SUR_SIM_UPDATE = "patrimoine-sim/transactions/sur-sim/update",
    POST_COMMANDE_PRODUIT_COMMANDES_DETAILS = "commande-produit/commandes/{numero_demande}/details",
    POST_SUPERVISION_OPERATIONS_TRAITEMENTS_SUIVIS_ABANDONNER_DEMANDE_SERVICE = 'supervision-operations/traitements-suivis/abandonner-demande-service',
    GET_SUPERVISION_OPERATIONS_TRAITEMENTS_SUIVIS_DOWNLOAD_MODELE_DATA = "supervision-operations/traitements-suivis/download-modele-data?operation={operation}&numeroDemande={numeroDemande}&token={tokenUser}",
    POST_SUPERVISION_OPERATIONS_TRAITEMENTS_SUIVIS_IDENTIFICATIONS_SIMS = 'supervision-operations/traitements-suivis/identifications-sims',
    POST_SUPERVISION_OPERATIONS_TRAITEMENTS_SUIVIS_CLOTURER_DEMANDE_SERVICE = 'supervision-operations/traitements-suivis/cloturer-demande-service',
    POST_SUPERVISION_OPERATIONS_TRAITEMENTS_SUIVIS_TRANSACTIONS_PAGE = 'supervision-operations/traitements-suivis/transactions?page={page}',
    GET_PATRIMOINE_SIM_TRANSACTIONS = 'patrimoine-sim/transactions/all?page={page}',
    GESTION_FACTURE_PAIMENTS_TRANSACTION = 'gestion-facture/paiments/transaction',
    GET_ALL_TRANSACTIONS = 'supervision-operations/traitements-suivis/demandes-services?page={page}',
    GET_DETAIL_TRANSACTION = 'gestion-transactions/details-transaction',
    GET_ALL_PRISE_EN_CHARGE = 'supervision-operations/prise-en-charge/all?page={page}',
    GET_ALL_DEMANDES = 'supervision-operations/file-attentes?page={page}',
    GET_ALL_CONTENCIEUX = 'supervision-operations/contentieux/all?page={page}',
    UPDATE_TRANSACTION = 'supervision-operations/traitements-suivis/modifier-transaction',
    CANCEL_TRANSACTION = 'supervision-operations/traitements-suivis/abandonner-transaction',
    CLOSE_TRANSACTION = 'supervision-operations/traitements-suivis/cloturer-transaction',
    GET_ALL_SLA = 'supervision-operations/engagement-sla/all',
    GET_ALL_NOTIFICATIONS = 'supervision-operations/centre-notifications/all',
    READ_NOTIFICATION = 'supervision-operations/centre-notifications/read',
    SAVE_MESSAGE = 'messagerie/boite-envoi/envoyer',
    UPDATE_MESSAGE = 'messagerie/boite-envoi/update',
    GET_ALL_MESSAGE_SENDER = 'messagerie/boite-envoi/all?page={page}',
    GET_ALL_MESSAGE_RECIEVE = 'messagerie/boite-reception/all?page={page}',
    DETAIL_MESSAGE_SENDER = 'messagerie/boite-envoi/details',
    DETAIL_MESSAGE_RECIEVE = 'messagerie/boite-reception/details',
    DOWNLOAD_MESSAGE = 'messagerie/boite-reception/telecharger',
    GET_ALL_DEMANDES_IDENTIFICATION = 'patrimoine-sim/demandes-services/all'
}

